### PR TITLE
Allow setting custom redirect URL

### LINKED ISSUE #191: Custom redirect URI
Hi @dermesser is there an example on how to add a custom redirect URI? I'm using the example from the custom flow and I realized that the token never gets to the URI, because of the `HTTPredirect` method.

### PR DESCRIPTION
**Pull request by k-bx**
Resolves https://github.com/dermesser/yup-oauth2/issues/191

### CODE REVIEW

**Comment by dermesser** [comment]
I think the `pub(crate)` on the flow_delegate field is what caused the misunderstanding - I totally missed it. Sorry about that and thanks for the PR!

**Comment by k-bx** [comment]
No problem. Feel free to dismiss this PR and reimplement more properly if needed.

**Comment by dermesser** [comment]
By the way, have you also tried the documented way of https://docs.rs/yup-oauth2/latest/yup_oauth2/struct.InstalledFlowAuthenticator.html: `InstalledFlowAuthenticator::builder(..).flow_delegate(..).build(..)`? It's been some time since I worked on that code, so it didn't come to mind immediately, either.

**Comment by k-bx** [comment]
@dermesser is it not shown at the link since it's not `pub(crate)` too?

**Comment by dermesser** [comment]
> @dermesser is it not shown at the link since it's not `pub(crate)` too?

Sorry, wrong link. I meant https://docs.rs/yup-oauth2/latest/yup_oauth2/authenticator/struct.AuthenticatorBuilder.html#method.flow_delegate-1 and supplying your own flow delegate, which gives you the opportunity of both specifying the redirect_uri and capturing the code.

What got me confused, I think, is that what you were trying to do is how things used to be done. Then it was refactored into the current "Java-Style", which made some things non-obvious.

**Comment by k-bx** [comment]
@dermesser you are right, this API worked!

image

Thank you for the hint.

**Comment by dermesser** [comment]
No worries, and sorry for taking so many detours :D

**Pull request closed without merging**
