### PR TITLE
fix(openssl): Update to 0.9.x

### PR DESCRIPTION
**Pull request by martell**
Hey so I tried to use this on MacOS and ran into the typical rust openssl include error.
This was fixed in openssl 0.9.4.
I figured updating yup-oauth2 would help others that run into a similar issue.

### CODE REVIEW

**Comment by dermesser** [comment]
I just reverted the fix again :( It turns out that some other dependencies still depend on openssl 0.7, and if we try and link both 0.7 and 0.9, the build fails:

```
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.9.6

  openssl-sys v0.7.17
```
funnily enough I couldn't reproduce it locally yet...

**Comment by martell** [comment]
Ahh yeah I noticed that on the build bots.
That has to do with the `Cargo.lock` file.
Running `cargo update` and committing the lock update should fix that.
I didn't want to include that in my PR for readability.

**Comment by dermesser** [comment]
Let me check again, because I did update the lockfile in db9824.

**Comment by dermesser** [comment]
aah, it's the tests.

**Comment by dermesser** [comment]
also, your patch fails a test. I'm fully reverting it now.

I have a pull request to yup-hyper-mock which will probably solve the openssl issue.

**Comment by dermesser** [comment]
when that pull request has been merged, please try reapplying your patch. And please run the tests.

Sorry for the mess, classic dependency hell.

**Comment by dermesser** [comment]
(this was the test failure: http://pastebin.com/raw/1v5MfDpq)

**Comment by Byron** [comment]
@dermesser v2.0 of yup-hyper-mock was just published - let's hope that you can now proceed.

**Comment by dermesser** [comment]
38fd851 fixes the last remains of this PR, especially the part where it changed RSA to HMAC, leading to 400 errors when requesting tokens. :-(

**Comment by martell** [comment]
Thanks for catching that @dermesser.
I started running into that today myself and found your fix.

**Pull request merged**
