### PR TITLE
Add an option to force the User to choose an Account

### PR DESCRIPTION
**Pull request by OMGeeky**
This option on the Installed flow forces the user to select an account when authorizing. This way the user can login with  Account A for something and Account B for something else, while not having to delete the tokens that are stored somewhere and allowing for multiple simultaneous logins.

I only implemented this for the Installed flow, maybe other flows could benefit from that too, I did not check.

### CODE REVIEW

**Comment by dermesser** [comment]
This assumes different scopes for the different accounts, right - so that the tokens are not overwritten? Thank you for the PR!

**Comment by OMGeeky** [comment]
Either that or they are stored in different files so they don't overlap at all by giving them each a different .persist_tokens_to_disk(path) generated with an internal user id  (in my case they might have different scopes, but not necessarily)

**Comment by OMGeeky** [comment]
If you need me to do anything more for this to be merged, I'd be happy to help.

**Comment by dermesser** [comment]
Thank you for your patience, I had some busy weeks :-)

**Pull request merged**
