### PR TITLE
feat(hyper-rustls): default hyper client support https and http

### LINKED ISSUE #179: The DefaultHyperClient does not support http - Issue with metadata server authentication
When using the InstanceMetadata authentication, the default hyper client only enforces https, and the call to the metadata server fails (returning the following error: `Token retrieval failed with error: error trying to connect: Unsupported scheme http`)

My current solution is to simply create a custom client as seen below:

``` rust
    match yup_oauth2::ApplicationDefaultCredentialsAuthenticator::with_client(
        opts,
        hyper::Client::builder().build(
            hyper_rustls::HttpsConnectorBuilder::new()
                .with_native_roots()
                .https_or_http()
                .enable_http1()
                .enable_http2()
                .build(),
        ),
    )
    .await
    {
        yup_oauth2::authenticator::ApplicationDefaultCredentialsTypes::InstanceMetadata(
            auth_builder,
        ) => {
            Ok(auth_builder.build().unwrap())
        }
        yup_oauth2::authenticator::ApplicationDefaultCredentialsTypes::ServiceAccount(auth_builder) => {
            Ok(auth_builder.build().await.unwrap())
            }
    }
```

### PR DESCRIPTION
**Pull request by pseguin2011**
Support http requests for the metadata server requests

Author: Pierre Seguin <pierre@orohealth.me>
Resolves: https://github.com/dermesser/yup-oauth2/issues/179

### CODE REVIEW

**Comment by dermesser** [comment]
Thank you for this PR; as an alternative, could you slightly refactor the current function to have one `build_hyper_client()` (like now), and another `build_insecure_http_hyper_client()`? Having a secure-by-default API is probably the right thing to do in a security-sensitive area like authentication, and it would allow users to choose for themselves.

In any case, thank you for taking the time to fix this!

**Comment by pseguin2011** [comment]
Should I also change the default http client built for `ApplicationDefaultCredentialsAuthenticator` ?

**Comment by dermesser** [comment]
Most of the checks fail due to #178 which renamed some type parameters. It should be enough to rebase and rename `C` into `S`.

> Should I also change the default http client built for ApplicationDefaultCredentialsAuthenticator ?

Sorry, which default client build do you mean?

**Comment by pseguin2011** [comment]
Well since the metadata server is **always** over http, should I also manage any default constructors for the authenticator? or would it be too risky?

**Comment by dermesser** [comment]
> Well since the metadata server is **always** over http, should I also manage any default constructors for the authenticator? or would it be too risky?

I think one blocking problem is that a "secure" builder is built by default (https://docs.rs/yup-oauth2/latest/src/yup_oauth2/authenticator.rs.html#441). I'm sorry for not having this in mind earlier (I've grown somewhat estranged from this code base, unfortunately - need to take the time to re-learn it).

Maybe, after all, your original PR (allowing HTTP) is still the best solution. I wonder if there is a practical threat scenario in which this would make a difference; if somebody has access to change your token URL, they could conceivably do more dangerous things in the first place.

I'm sorry for the confusion! This crate has grown quite complex in the meantime.

**Comment by pseguin2011** [comment]
After giving it some thought, I realize it is probably better to remain secure by default and have a deliberate implementation of an insecure client when using the metadata server.

So here is my proposal:
We close this PR and simply add additional documentation for examples on using the library with the metadata server

**Comment by dermesser** [comment]
Additional documentation sounds good, although note that my commit already enabled HTTP fallback (for all I can see, the token URLs etc. are supplied by the application developer, and they should be HTTPS).

**Pull request closed without merging**
