### PR TITLE
Update hyper-native-tls from 0.2 to 0.3

### PR DESCRIPTION
**Pull request by edelangh**
It fix some issue with openssl

Without, I've this issue:

```
error: failed to run custom build command for `openssl v0.9.24`                                                       
process didn't exit successfully: `~/MyProject/target/debug/build/openssl-25ecc6c570fa312a/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
```

### CODE REVIEW

**Comment by dermesser** [comment]
Thank you!

**Comment by edelangh** [comment]
Thank you too!

**Comment by balajisivaraman** [comment]
@dermesser, Any idea when we'll have a new release with this update? I'm currently trying to use [google-calendar3](https://crates.io/crates/google-calendar3) in an application and cannot do so because of the OpenSSL issue. It would be helpful if we can get a minor version release with this fix.

Thanks in advance.

**Comment by dermesser** [comment]
Apologies for the delay, I've published 1.0.9 now.

**Pull request merged**
